= DotMatrix DLR2416 Library for Arduino =

A library to control the DLR2416 or DLR3416, 4 red displays with 5x7 dot matrix, alphanumeric Intelligent Display with memory, decoder and driver.

The integrated circuit DLR2416 (red), DLG2416 (green) contains memory, ASCII ROM decoder, multiplexing circuitry and drivers. The data entry is asynchronous. A display system can be built using any number of DLx2416 since each digit can be addressed indepentdently and will continue to display the character last stored.

This libray contains a simple example how using the DLR2416 with an Arduino UNO.

== License ==

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
